name: Build mod

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Gradle build (download Gradle if missing)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
